entry_point: 0x8004f45
fork_points:
- 0x8004198
include:
- ./syms.yml
- ../../../../.local/lib/python3.10/site-packages/semu_fuzz/helper/configs/hw/cortexm_memory.yml
initial_sp: 0x20005000
isr_vector: 0x8004f45
memory_map:
  flash:
    base_addr: 0x8000000
    file: Drone.bin
    permissions: r-x
    size: 0x2000000
rules: ../../../rules/f103.txt
