entry_point: 0x80056b9
fork_points: []
include:
- ./syms.yml
- ../../../../.local/lib/python3.10/site-packages/semu_fuzz/helper/configs/hw/cortexm_memory.yml
initial_sp: 0x20005000
isr_vector: 0x80056b9
memory_map:
  flash:
    base_addr: 0x8000000
    file: Robot.bin
    permissions: r-x
    size: 0x2000000
rules: ../../../rules/f103.txt
