entry_point: 0x80005a5
fork_points:
- 0x8000d2c
include:
- ./syms.yml
- ../../../../.local/lib/python3.10/site-packages/semu_fuzz/helper/configs/hw/cortexm_memory.yml
initial_sp: 0x20030000
isr_vector: 0x80005a5
memory_map:
  flash:
    base_addr: 0x8000000
    file: LwIP_TCP_Echo_Client.bin
    permissions: r-x
    size: 0x2000000
rules: ../../../rules/f429.txt
