entry_point: 0x80bfd
fork_points:
- 0x81276
- 0x815e0
include:
- ./syms.yml
- ../../../../.local/lib/python3.10/site-packages/semu_fuzz/helper/configs/hw/cortexm_memory.yml
initial_sp: 0x20088000
isr_vector: 0x80bfd
memory_map:
  flash:
    base_addr: 0x80000
    file: Steering_Control.bin
    permissions: r-x
    size: 0x2000000
rules: ../../../rules/sam3x.txt
